[package]
name = "portos-fs"
version.workspace = true
edition.workspace = true

[[bin]]
name = "portos-fs"
path = "src/main.rs"

[dependencies]
globset = "0.4"
ignore = "0.4"
portos-bulk-api = { path = "../bulk-api" }
portos-proto = { path = "../../crates/portos-proto" }
portos-sdk = { path = "../../crates/portos-sdk" }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
portos-kernel = { path = "../../crates/portos-kernel" }
