[package]
name = "portos-shell"
version.workspace = true
edition.workspace = true

[[bin]]
name = "portos-shell"
path = "src/main.rs"

[dependencies]
nix = { workspace = true }
portos-bulk-api = { path = "../bulk-api" }
portos-proto = { path = "../../crates/portos-proto" }
portos-sdk = { path = "../../crates/portos-sdk" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
portos-kernel = { path = "../../crates/portos-kernel" }
