//! portos-fs: the file tree as verbs.
//!
//! Five verbs, one tree, and one discipline that matters more than any of
//! them: **a result the model might not read does not enter its context.** A
//! source file, a grep over a repository, a directory listing — each can be
//! anywhere from a line to a megabyte, and the difference between a usable
//! agent and an unusable one is which of those the model is made to carry.
//! Every bulky answer here goes through `portos_sdk::bulk::Sink`, which is the
//! same decision the browser driver makes, in the same shape.
//!
//! The tree is named once, in `PORTOS_FS_ROOT`, and every path is relative to
//! it. See `scope.rs` for what that does and does not promise.
//!
//! Walking respects `.gitignore`. That is not a nicety: a grep that does not
//! is a grep that reads `target/`, and in this repository alone that is
//! several gigabytes of machine-generated bytes nobody asked about.
//!
//! The interface is `drivers/fs`; this is its first implementation.
//!
//! Config (from the launch spec): `{"root": "/path/to/tree"}`

mod scope;

use ignore::WalkBuilder;
use portos_abi::Label;
use portos_abi::wire::Payload;
use portos_fs_api::{
    self as fs, Entry, GlobArgs, GrepArgs, Kind, ListArgs, Listing, Match, Matches, Paths,
    ReadArgs, WriteArgs, WriteReply,
};
use portos_sdk::bulk::Sink;
use portos_sdk::{CallError, CallResult, KernelClient, Plugin};
use scope::Scope;
use serde::Deserialize;
use std::os::unix::fs::PermissionsExt;
use std::sync::Arc;

/// Caps on how much one call may answer with. They bound the *count* of
/// results; `Sink` bounds their bytes. Both are needed: ten thousand paths
/// are small individually and ruinous together.
const MAX_ENTRIES: usize = 1000;
const MAX_MATCHES: usize = 200;
/// A matched line longer than this is cut. Minified JavaScript is one line.
const MAX_LINE: usize = 400;

/// What this driver needs to know, which is one thing.
#[derive(Deserialize)]
struct Config {
    /// The tree it serves. See `scope.rs` for what that does and does not
    /// promise.
    root: String,
}

fn main() -> std::io::Result<()> {
    let cfg: Config = portos_sdk::config::config().map_err(std::io::Error::other)?;
    let root = std::fs::canonicalize(&cfg.root)
        .map_err(|e| std::io::Error::other(format!("fs root {:?}: {e}", cfg.root)))?;
    eprintln!("[fs] serving {}", root.display());

    let scope = Arc::new(Scope::new(root));
    let sink = Sink::default();
    let (s1, s2, s3, s4, s5) = (
        scope.clone(),
        scope.clone(),
        scope.clone(),
        scope.clone(),
        scope,
    );

    // What each verb says about itself comes from the interface, so this
    // plugin advertises `drivers/fs` rather than its own wording of it.
    let tools = fs::tools();
    portos_sdk::serve(
        Plugin::new("portos-fs")
            .implement(&fs::READ, &tools[&fs::READ], move |args, client| {
                read(&s1, &sink, client, args.parse()?)
            })
            .implement(&fs::WRITE, &tools[&fs::WRITE], move |args, client| {
                write(&s2, client, args.parse()?)
            })
            .implement(&fs::LIST, &tools[&fs::LIST], move |args, _client| {
                list(&s3, args.parse()?)
            })
            .implement(&fs::GLOB, &tools[&fs::GLOB], move |args, _client| {
                glob(&s4, args.parse()?)
            })
            .implement(&fs::GREP, &tools[&fs::GREP], move |args, _client| {
                grep(&s5, args.parse()?)
            }),
        |_topic, _data| {},
    )
}

// ------------------------------------------------------------------ read ----

fn read(scope: &Scope, sink: &Sink, client: &KernelClient, a: ReadArgs) -> CallResult {
    let full = scope.resolve(&a.path).map_err(CallError::from)?;
    let bytes = std::fs::read(&full).map_err(|e| CallError::from(format!("{}: {e}", a.path)))?;
    let start = (a.offset as usize).min(bytes.len());
    let end = match a.len {
        Some(n) => (start + n as usize).min(bytes.len()),
        None => bytes.len(),
    };
    // Lossy on purpose: a driver that refuses to show a file because one byte
    // is not UTF-8 is less useful than one that shows it with a replacement
    // character. The bytes themselves are intact in the CAS when it spills.
    let text = String::from_utf8_lossy(&bytes[start..end]).into_owned();
    let labels = Label::with_integ(&format!("file:{}", a.path));
    Ok(Payload::of(&sink.deliver(
        client,
        &text,
        "text/plain",
        Some(labels),
    )?)?)
}

// ----------------------------------------------------------------- write ----

fn write(scope: &Scope, client: &KernelClient, a: WriteArgs) -> CallResult {
    let full = scope.resolve(&a.path).map_err(CallError::from)?;
    if a.create_dirs {
        if let Some(parent) = full.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| CallError::from(format!("{}: {e}", a.path)))?;
        }
    }
    let bytes = match (&a.content, &a.artifact) {
        (Some(text), None) => {
            std::fs::write(&full, text.as_bytes())
                .map_err(|e| CallError::from(format!("{}: {e}", a.path)))?;
            text.len() as u64
        }
        // Copied file to file: the bytes are already a file, so there is no
        // reason for them to travel through this process at all.
        (None, Some(id)) => {
            let src = client
                .locate(id)
                .map_err(|e| CallError::from(format!("artifact {id}: {e}")))?;
            std::fs::copy(&src, &full).map_err(|e| CallError::from(format!("{}: {e}", a.path)))?;
            // A stored object is read-only; a file in someone's tree is not.
            let mut perms = std::fs::metadata(&full)
                .map_err(|e| CallError::from(e.to_string()))?
                .permissions();
            perms.set_mode(0o644);
            let _ = std::fs::set_permissions(&full, perms);
            std::fs::metadata(&full).map(|m| m.len()).unwrap_or(0)
        }
        _ => {
            return Err(CallError::from(
                "fs::write needs exactly one of `content` and `artifact`",
            ));
        }
    };
    Ok(Payload::of(&WriteReply {
        path: a.path,
        bytes,
    })?)
}

// ------------------------------------------------------------------ list ----

fn list(scope: &Scope, a: ListArgs) -> CallResult {
    let base = scope
        .resolve(a.path.as_deref().unwrap_or("."))
        .map_err(CallError::from)?;
    let mut entries = Vec::new();
    let mut truncated = false;
    for item in WalkBuilder::new(&base).max_depth(Some(a.depth)).build() {
        let item = match item {
            Ok(i) => i,
            Err(_) => continue, // an unreadable entry is not a failed listing
        };
        if item.path() == base {
            continue;
        }
        if entries.len() >= MAX_ENTRIES {
            truncated = true;
            break;
        }
        let meta = item.metadata().ok();
        let is_dir = meta.as_ref().map(|m| m.is_dir()).unwrap_or(false);
        entries.push(Entry {
            path: scope.relative(item.path()),
            kind: if is_dir { Kind::Dir } else { Kind::File },
            size: (!is_dir).then(|| meta.as_ref().map(|m| m.len()).unwrap_or(0)),
        });
    }
    entries.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(Payload::of(&Listing { entries, truncated })?)
}

// ------------------------------------------------------------------ glob ----

fn glob(scope: &Scope, a: GlobArgs) -> CallResult {
    let matcher = globset::Glob::new(&a.pattern)
        .map_err(|e| CallError::from(format!("bad glob {:?}: {e}", a.pattern)))?
        .compile_matcher();
    let max = a.max.unwrap_or(MAX_ENTRIES).min(MAX_ENTRIES);
    let mut paths = Vec::new();
    let mut truncated = false;
    for item in WalkBuilder::new(scope.root()).build().flatten() {
        if item.file_type().is_some_and(|t| t.is_dir()) {
            continue;
        }
        let rel = scope.relative(item.path());
        if matcher.is_match(&rel) {
            if paths.len() >= max {
                truncated = true;
                break;
            }
            paths.push(rel);
        }
    }
    paths.sort();
    Ok(Payload::of(&Paths { paths, truncated })?)
}

// ------------------------------------------------------------------ grep ----

fn grep(scope: &Scope, a: GrepArgs) -> CallResult {
    let re = regex_lite(&a.pattern)?;
    let filter = match &a.glob {
        Some(g) => Some(
            globset::Glob::new(g)
                .map_err(|e| CallError::from(format!("bad glob {g:?}: {e}")))?
                .compile_matcher(),
        ),
        None => None,
    };
    let max = a.max.unwrap_or(MAX_MATCHES).min(MAX_MATCHES);
    let mut matches = Vec::new();
    let mut truncated = false;

    'walk: for item in WalkBuilder::new(scope.root()).build().flatten() {
        if item.file_type().is_some_and(|t| t.is_dir()) {
            continue;
        }
        let rel = scope.relative(item.path());
        if filter.as_ref().is_some_and(|f| !f.is_match(&rel)) {
            continue;
        }
        // Binary files are skipped rather than shown as replacement
        // characters: a match inside one is not something a caller can act on.
        let Ok(text) = std::fs::read_to_string(item.path()) else {
            continue;
        };
        for (i, line) in text.lines().enumerate() {
            if !re.is_match(line) {
                continue;
            }
            if matches.len() >= max {
                truncated = true;
                break 'walk;
            }
            matches.push(Match {
                path: rel.clone(),
                line: i + 1,
                text: truncate(line, MAX_LINE),
            });
        }
    }
    Ok(Payload::of(&Matches { matches, truncated })?)
}

fn regex_lite(pattern: &str) -> Result<regex::Regex, CallError> {
    regex::Regex::new(pattern).map_err(|e| CallError::from(format!("bad pattern: {e}")))
}

fn truncate(s: &str, n: usize) -> String {
    match s.char_indices().nth(n) {
        Some((end, _)) => format!("{}…", &s[..end]),
        None => s.to_string(),
    }
}
