//! portos-fs: the file tree as verbs.
//!
//! Five verbs, one tree, and one discipline that matters more than any of
//! them: **a result the model might not read does not enter its context.** A
//! source file, a grep over a repository, a directory listing — each can be
//! anywhere from a line to a megabyte, and the difference between a usable
//! agent and an unusable one is which of those the model is made to carry.
//! Every bulky answer here goes through `portos_bulk_api::Sink`, which is the
//! same decision the browser driver makes, in the same shape.
//!
//! The tree is named once, in `PORTOS_FS_ROOT`, and every path is relative to
//! it. See `scope.rs` for what that does and does not promise.
//!
//! Walking respects `.gitignore`. That is not a nicety: a grep that does not
//! is a grep that reads `target/`, and in this repository alone that is
//! several gigabytes of machine-generated bytes nobody asked about.
//!
//! Config (environment):
//!   PORTOS_FS_ROOT   required — the tree this driver serves

mod scope;

use ignore::WalkBuilder;
use portos_bulk_api::Sink;
use portos_proto::Label;
use portos_proto::wire::{Payload, ToolMeta};
use portos_sdk::{CallError, CallResult, KernelClient, Plugin};
use scope::Scope;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeMap;

/// Caps on how much one call may answer with. They bound the *count* of
/// results; `Sink` bounds their bytes. Both are needed: ten thousand paths
/// are small individually and ruinous together.
const MAX_ENTRIES: usize = 1000;
const MAX_MATCHES: usize = 200;
/// A matched line longer than this is cut. Minified JavaScript is one line.
const MAX_LINE: usize = 400;

fn main() -> std::io::Result<()> {
    let root = std::env::var("PORTOS_FS_ROOT")
        .map_err(|_| std::io::Error::other("PORTOS_FS_ROOT unset"))?;
    let root = std::fs::canonicalize(&root)
        .map_err(|e| std::io::Error::other(format!("PORTOS_FS_ROOT {root:?}: {e}")))?;
    eprintln!("[fs] serving {}", root.display());

    let scope = Scope::new(root);
    let sink = Sink::default();

    portos_sdk::serve(
        Plugin::new("portos-fs", VERBS).with_tools(tools()),
        move |verb, args, client| dispatch(&scope, &sink, client, verb.short(), args),
        |_topic, _data| {},
    )
}

const VERBS: &[&str] = &["fs::read", "fs::write", "fs::list", "fs::glob", "fs::grep"];

fn dispatch(
    scope: &Scope,
    sink: &Sink,
    client: &KernelClient,
    verb: &str,
    args: &Payload,
) -> CallResult {
    match verb {
        "read" => read(scope, sink, client, args.parse()?),
        "write" => write(scope, args.parse()?),
        "list" => list(scope, args.parse()?),
        "glob" => glob(scope, args.parse()?),
        "grep" => grep(scope, args.parse()?),
        other => Err(CallError::from(format!("unknown verb: {other}"))),
    }
}

// ------------------------------------------------------------------ read ----

#[derive(Deserialize)]
struct ReadArgs {
    path: String,
    #[serde(default)]
    offset: u64,
    #[serde(default)]
    len: Option<u64>,
}

fn read(scope: &Scope, sink: &Sink, client: &KernelClient, a: ReadArgs) -> CallResult {
    let full = scope.resolve(&a.path).map_err(CallError::from)?;
    let bytes = std::fs::read(&full).map_err(|e| CallError::from(format!("{}: {e}", a.path)))?;
    let start = (a.offset as usize).min(bytes.len());
    let end = match a.len {
        Some(n) => (start + n as usize).min(bytes.len()),
        None => bytes.len(),
    };
    // Lossy on purpose: a driver that refuses to show a file because one byte
    // is not UTF-8 is less useful than one that shows it with a replacement
    // character. The bytes themselves are intact in the CAS when it spills.
    let text = String::from_utf8_lossy(&bytes[start..end]).into_owned();
    let labels = Label::with_integ(&format!("file:{}", a.path));
    Ok(Payload::of(&sink.deliver(
        client,
        &text,
        "text/plain",
        Some(labels),
    )?)?)
}

// ----------------------------------------------------------------- write ----

#[derive(Deserialize)]
struct WriteArgs {
    path: String,
    content: String,
    #[serde(default)]
    create_dirs: bool,
}

#[derive(Serialize)]
struct WriteReply {
    path: String,
    bytes: u64,
}

fn write(scope: &Scope, a: WriteArgs) -> CallResult {
    let full = scope.resolve(&a.path).map_err(CallError::from)?;
    if a.create_dirs {
        if let Some(parent) = full.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| CallError::from(format!("{}: {e}", a.path)))?;
        }
    }
    std::fs::write(&full, a.content.as_bytes())
        .map_err(|e| CallError::from(format!("{}: {e}", a.path)))?;
    Ok(Payload::of(&WriteReply {
        path: a.path,
        bytes: a.content.len() as u64,
    })?)
}

// ------------------------------------------------------------------ list ----

#[derive(Deserialize)]
struct ListArgs {
    #[serde(default)]
    path: Option<String>,
    /// 1 means this directory only, which is what a caller almost always
    /// means by "list".
    #[serde(default = "one")]
    depth: usize,
}

fn one() -> usize {
    1
}

#[derive(Serialize)]
struct Entry {
    path: String,
    kind: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    size: Option<u64>,
}

#[derive(Serialize)]
struct Listing {
    entries: Vec<Entry>,
    truncated: bool,
}

fn list(scope: &Scope, a: ListArgs) -> CallResult {
    let base = scope
        .resolve(a.path.as_deref().unwrap_or("."))
        .map_err(CallError::from)?;
    let mut entries = Vec::new();
    let mut truncated = false;
    for item in WalkBuilder::new(&base).max_depth(Some(a.depth)).build() {
        let item = match item {
            Ok(i) => i,
            Err(_) => continue, // an unreadable entry is not a failed listing
        };
        if item.path() == base {
            continue;
        }
        if entries.len() >= MAX_ENTRIES {
            truncated = true;
            break;
        }
        let meta = item.metadata().ok();
        let is_dir = meta.as_ref().map(|m| m.is_dir()).unwrap_or(false);
        entries.push(Entry {
            path: scope.relative(item.path()),
            kind: if is_dir { "dir" } else { "file" },
            size: (!is_dir).then(|| meta.as_ref().map(|m| m.len()).unwrap_or(0)),
        });
    }
    entries.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(Payload::of(&Listing { entries, truncated })?)
}

// ------------------------------------------------------------------ glob ----

#[derive(Deserialize)]
struct GlobArgs {
    pattern: String,
    #[serde(default)]
    max: Option<usize>,
}

#[derive(Serialize)]
struct Paths {
    paths: Vec<String>,
    truncated: bool,
}

fn glob(scope: &Scope, a: GlobArgs) -> CallResult {
    let matcher = globset::Glob::new(&a.pattern)
        .map_err(|e| CallError::from(format!("bad glob {:?}: {e}", a.pattern)))?
        .compile_matcher();
    let max = a.max.unwrap_or(MAX_ENTRIES).min(MAX_ENTRIES);
    let mut paths = Vec::new();
    let mut truncated = false;
    for item in WalkBuilder::new(scope.root()).build().flatten() {
        if item.file_type().is_some_and(|t| t.is_dir()) {
            continue;
        }
        let rel = scope.relative(item.path());
        if matcher.is_match(&rel) {
            if paths.len() >= max {
                truncated = true;
                break;
            }
            paths.push(rel);
        }
    }
    paths.sort();
    Ok(Payload::of(&Paths { paths, truncated })?)
}

// ------------------------------------------------------------------ grep ----

#[derive(Deserialize)]
struct GrepArgs {
    pattern: String,
    /// Restrict to paths matching this glob, e.g. `**/*.rs`.
    #[serde(default)]
    glob: Option<String>,
    #[serde(default)]
    max: Option<usize>,
}

#[derive(Serialize)]
struct Match {
    path: String,
    line: usize,
    text: String,
}

#[derive(Serialize)]
struct Matches {
    matches: Vec<Match>,
    truncated: bool,
}

fn grep(scope: &Scope, a: GrepArgs) -> CallResult {
    let re = regex_lite(&a.pattern)?;
    let filter = match &a.glob {
        Some(g) => Some(
            globset::Glob::new(g)
                .map_err(|e| CallError::from(format!("bad glob {g:?}: {e}")))?
                .compile_matcher(),
        ),
        None => None,
    };
    let max = a.max.unwrap_or(MAX_MATCHES).min(MAX_MATCHES);
    let mut matches = Vec::new();
    let mut truncated = false;

    'walk: for item in WalkBuilder::new(scope.root()).build().flatten() {
        if item.file_type().is_some_and(|t| t.is_dir()) {
            continue;
        }
        let rel = scope.relative(item.path());
        if filter.as_ref().is_some_and(|f| !f.is_match(&rel)) {
            continue;
        }
        // Binary files are skipped rather than shown as replacement
        // characters: a match inside one is not something a caller can act on.
        let Ok(text) = std::fs::read_to_string(item.path()) else {
            continue;
        };
        for (i, line) in text.lines().enumerate() {
            if !re.is_match(line) {
                continue;
            }
            if matches.len() >= max {
                truncated = true;
                break 'walk;
            }
            matches.push(Match {
                path: rel.clone(),
                line: i + 1,
                text: truncate(line, MAX_LINE),
            });
        }
    }
    Ok(Payload::of(&Matches { matches, truncated })?)
}

fn regex_lite(pattern: &str) -> Result<regex::Regex, CallError> {
    regex::Regex::new(pattern).map_err(|e| CallError::from(format!("bad pattern: {e}")))
}

fn truncate(s: &str, n: usize) -> String {
    match s.char_indices().nth(n) {
        Some((end, _)) => format!("{}…", &s[..end]),
        None => s.to_string(),
    }
}

// ----------------------------------------------------------------- tools ----

/// What the model is told. These descriptions are the driver's half of the
/// tool surface — the kernel joins them with whatever the caller was granted.
fn tools() -> BTreeMap<&'static str, ToolMeta> {
    let mut t = BTreeMap::new();
    t.insert(
        "fs::read",
        meta(
            "Read a text file. Paths are relative to the driver's root. A large \
             file comes back as {handle, size, preview} instead of {text}: pass \
             the handle to artifact::read for the rest, or use offset/len here.",
            json!({
                "type": "object",
                "properties": {
                    "path": {"type": "string"},
                    "offset": {"type": "integer", "description": "byte offset"},
                    "len": {"type": "integer", "description": "byte count"},
                },
                "required": ["path"],
            }),
        ),
    );
    t.insert(
        "fs::write",
        meta(
            "Write a text file, replacing it if it exists. Set create_dirs to \
             make missing parent directories.",
            json!({
                "type": "object",
                "properties": {
                    "path": {"type": "string"},
                    "content": {"type": "string"},
                    "create_dirs": {"type": "boolean"},
                },
                "required": ["path", "content"],
            }),
        ),
    );
    t.insert(
        "fs::list",
        meta(
            "List a directory. depth 1 is the directory itself; raise it to \
             descend. Ignored files (.gitignore) are not listed.",
            json!({
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "defaults to the root"},
                    "depth": {"type": "integer"},
                },
            }),
        ),
    );
    t.insert(
        "fs::glob",
        meta(
            "Find files by glob pattern, e.g. `**/*.rs` or `src/**/mod.rs`. \
             Matched against paths relative to the root.",
            json!({
                "type": "object",
                "properties": {
                    "pattern": {"type": "string"},
                    "max": {"type": "integer"},
                },
                "required": ["pattern"],
            }),
        ),
    );
    t.insert(
        "fs::grep",
        meta(
            "Search file contents by regular expression, returning {path, line, \
             text} for each match. Narrow it with a glob. Ignored files and \
             binary files are skipped.",
            json!({
                "type": "object",
                "properties": {
                    "pattern": {"type": "string", "description": "regular expression"},
                    "glob": {"type": "string", "description": "restrict to matching paths"},
                    "max": {"type": "integer"},
                },
                "required": ["pattern"],
            }),
        ),
    );
    t
}

fn meta(description: &str, schema: serde_json::Value) -> ToolMeta {
    ToolMeta {
        description: description.to_string(),
        schema: Payload::of(&schema).ok(),
    }
}
