[package]
name = "portos-modeld"
version.workspace = true
edition.workspace = true

[[bin]]
name = "portos-modeld"
path = "src/main.rs"

[dependencies]
portos-egress-api = { path = "../egress-api" }
portos-model-api = { path = "../model-api" }
portos-proto = { path = "../../crates/portos-proto" }
portos-sdk = { path = "../../crates/portos-sdk" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
portos-kernel = { path = "../../crates/portos-kernel" }
